### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by adamkennedy** [nextflow-io/nextflow-s3fs#19]
The README.md says this is GPL3.

The POM.xml says it is Apache 2.

And it's a fork from a project which was itself Apache 2.

What license is this?

**Comment by pditommaso** [comment]
Yeah, there's a bit of confusion. To be fair the fork it's MIT. 

BTW, it's currently GPL, but it could be a good opportunity to move it Apache.

**Comment by pditommaso** [comment]
Solved 70f1fb5.
